name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LANG:
          - "de_DE.UTF-8"
          - "en_US.UTF-8"

    env:
      LANG: ${{ matrix.LANG }}

    steps:
    - uses: actions/checkout@v4

    - name: Set locale
      run: |
          sudo locale-gen ${{ matrix.LANG }}
          sudo update-locale LANG=${{ matrix.LANG }}
    - name: date
      run: |
          date

    - run: |
        sudo apt-get -qq update && sudo apt-get install -yqq libreoffice libreoffice-l10n-de lloconv
    - run: libreoffice --headless --version

    - run: lloconv foo.ods bar.csv
    - run: lloconv foo.ods bar.html
    - run: lloconv foo.ods bar.fods


    - run: lloconv foo.fods baz.csv
    - run: lloconv foo.fods baz.html
    - run: lloconv foo.fods baz.ods


    - run: cat bar.csv
    - run: cat bar.html
    - run: cat bar.fods

    - run: cat baz.csv
    - run: cat baz.html
